Arduino lib
Sensirion/embedded-svm40 pull request #14
Opened 2020-10-02 14:18 UTC by Zifzaf

Check the following:

 - [ ] Breaking changes marked in commit message
 - [ ] Changelog updated
 - [ ] Code style cleaned (ran `make style-fix`)
 - [ ] Tested on actual hardware

2020-10-05 11:26 UTC, abrauchli requested changes

2020-10-05 11:26 UTC, abrauchli commented on Makefile
> +	sed -i -e "s/svm40.h/$${pkgname}.h/g" "$${pkgdir}/src/$${pkgname}.c" && \
I'd rather not rename the files, it should not be an Arduino-conforming driver, it's enough to be drop-in compatible for now.

2020-10-05 11:26 UTC, abrauchli commented on svm40/.arduino/svm40_example_usage_arduino.ino
> +  }
That should be in a loop, otherwise the readout in `loop()` doesn't make much sense

```suggestion
  do {
    err = svm40_start_continuous_measurement();
    if (err) {
      Serial.print("Error starting measurement: ");
      Serial.println(err);
      delay(100);
    }
  } while(err);
```

2020-10-05 11:26 UTC, abrauchli commented on svm40/.arduino/svm40_example_usage_arduino.ino
> +  int16_t temperature;
can we use `temperature_celsius` ?

2020-11-02 11:14 UTC, Zifzaf commented on Makefile
> +	export pkgname="SVM40Arduino" && \
changed it to that :)

2020-11-02 11:16 UTC, Zifzaf commented on Makefile
> +	sed -i -e "s/svm40.h/$${pkgname}.h/g" "$${pkgdir}/src/$${pkgname}.c" && \
I see the point, but in Arduino libraries its necessary that there is a file named the same as the whole library. We could name the library just svm40 but then we run into issues in the release generation because the default release is already name that way.

2020-11-02 11:58 UTC, abrauchli commented on Makefile
> +	sed -i -e "s/svm40.h/$${pkgname}.h/g" "$${pkgdir}/src/$${pkgname}.c" && \
Thanks, point taken, I did not consider that.

2020-11-02 13:59 UTC, abrauchli requested changes

2020-11-02 13:59 UTC, abrauchli commented on svm40/.arduino/library.properties
> +name=SVM40Arduino
`arduino-svm40` ?

2020-11-02 13:59 UTC, abrauchli commented on svm40/.arduino/library.properties
> +paragraph=Allows Arduino boards to use the SVM40 sensor. Underlying is the normal embedded driver from Sensirion.
```suggestion
sentence=Support for Sensirion's SVM40 gas sensor module.
paragraph=Measures humidity, temperature and Volatile Organic Compounds (VOC) in the air.
```

2020-11-02 13:59 UTC, abrauchli commented on svm40/.arduino/library.properties
> +url=https://www.sensirion.com
```suggestion
url=https://developer.sensirion.com
```

2020-11-02 13:59 UTC, abrauchli commented on svm40/.arduino/svm40_example_usage_arduino.ino
> +    Serial.println( temperature_celsius / 200.0f);
```suggestion
    Serial.println(temperature_celsius / 200.0f);
```

2021-01-06 14:44 UTC, rnestler commented
Will be replaced by separate generated Arduino libraries in the near future.

2021-01-06 14:44 UTC, closed without merging