Add arduino release
Sensirion/embedded-svm40 pull request #17
Opened 2020-11-02 14:50 UTC by Zifzaf

Check the following:

 - [ ] Breaking changes marked in commit message
 - [ ] Changelog updated
 - [ ] Code style cleaned (ran `make style-fix`)
 - [ ] Tested on actual hardware

2020-11-02 15:48 UTC, rnestler requested changes

2020-11-02 15:48 UTC, rnestler commented on Makefile
> +	cd release && zip -r "$${pkgname}.zip" "$${pkgname}" && cd -
The `ln` step is missing, so the `svm40_arduino` target.

2020-11-02 15:48 UTC, rnestler commented on Makefile
> +release/svm40_arduino: prepare
This target should also be added to the `release_drivers` so it gets built with `make release`.

2020-11-02 15:48 UTC, rnestler commented on Makefile
> +	cp README-ARDUINO.md "release/$${pkgname}" && \
The file `README-ARDUINO.md` doesn't exist.

2020-11-02 15:48 UTC, rnestler commented on README-ARDUINO.rst
> +don't worry about that one.
`NC` means "No Connection" so maybe explain just state that :slightly_smiling_face:

2020-11-02 15:48 UTC, rnestler commented on svm40/svm40_example_usage_arduino.ino
> +    return;
I'm not sure if this `return` makes sense here. It will just start looping. Maybe just remove it, as it should never happen that the get driver version fails.

2020-11-02 15:48 UTC, rnestler commented on svm40/svm40_example_usage_arduino.ino
> +  if (err != NO_ERROR) {
I'd use `if (err)` like in all the other if statements or `if (err != NO_ERROR)` everywhere.

2020-11-02 15:48 UTC, rnestler commented on svm40/svm40_example_usage_arduino.ino
> +    Serial.print("SVM40 driver version");
```suggestion
    Serial.print("SVM40 driver version: ");
```

2020-11-02 16:53 UTC, abrauchli requested changes

2020-11-02 16:53 UTC, abrauchli commented on Makefile
> +	cp README-ARDUINO.md "release/$${pkgname}" && \
I think it's part of this PR ;)

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +Preperation
```suggestion
Preparation
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +To flash the Arduino Board with a program you need to download and install the
```suggestion
To flash the Arduino Board you need to download and install the
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +---------------------
```suggestion
Connecting the Sensor Module
----------------------------
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +You can find these on the Arduino website. Look for SDA to connect the modules
```suggestion
out which pins are the correct ones, consult the pinout of your specific board
on the Arduino website. Look for SDA to connect the modules
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +Sensirion Github page (https://github.com/Sensirion/embedded-svm40/releases).
```suggestion
release page (https://github.com/Sensirion/embedded-svm40/releases).
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +last Boards Manager. Then you can type the name of your board in the search bar
```suggestion
flash them via the Arduino IDE. This is done selecting the Menu items `Tools > Boards >
Boards Manager`. Then you can type the name of your board in the search bar
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +and install the upcoming package.
```suggestion
and install the respective package.
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +the Tools, Board menu that corresponds to your Arduino board. Finally you also
```suggestion
the `Tools > Board` menu that corresponds to your Arduino board. Finally you also
```
double check if that's what you meant

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +indicating that a board is connected it's likely to be COM3. To now upload your
```suggestion
indicating that a board is connected it's likely to be one of the `COMxx` ports, where `xx` is a number. To now upload your
```

To me it sounds rather unlikely that it's COM3.. that highly depends on what's plugged in

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +Serial Monitor. If everything worked fine and your Arduino is still connected
```suggestion
To look at the senor data open the serial monitor by navigating to `Tools >
Serial Monitor`. If everything worked fine and your Arduino is still connected
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +navigate to Tools, Port and select the one indicating that your board is
```suggestion
navigate to `Tools > Port` and select the one indicating that your board is
```

2020-11-02 16:53 UTC, abrauchli commented on README-ARDUINO.rst
> +Check if you connected the module correctly, so all cables are fully
```suggestion
Check if you connected the module correctly, and all cables are fully
```

2020-11-02 16:53 UTC, abrauchli commented on svm40/svm40_example_usage_arduino.ino
> +    Serial.println( temperature_celsius / 200.0f);
```suggestion
    Serial.println(temperature_celsius / 200.0f);
```

2020-11-03 07:05 UTC, Zifzaf commented on Makefile
> +release/svm40_arduino: prepare
Done.

2020-11-03 07:23 UTC, Zifzaf commented on README-ARDUINO.rst
> +indicating that a board is connected it's likely to be COM3. To now upload your
That was from the Arduino Website ... but since then I think they changed it ... now it everything but COM3 ':)
I now just got rid of the sentence.

2020-11-03 14:22 UTC, abrauchli approved these changes
I quickly test compiled and it looks all good. Nice work.

2020-11-04 08:27 UTC, rnestler commented on Makefile
> +	cp README-ARDUINO.md "release/$${pkgname}" && \
You mean it should :wink:

2020-11-04 13:16 UTC, rnestler commented on README-ARDUINO.rst
> +Serial Monitor`. If everything worked fine and your Arduino is still connected
What's the point of the \` ? They don't render in restructured text https://github.com/Sensirion/embedded-svm40/blob/04b067388c5b58ea7285a8201c46474d01e6f24d/README-ARDUINO.rst.

According to https://docutils.sourceforge.io/docs/user/rst/quickref.html \`\` are used for

> The rendering and meaning of interpreted text is domain- or application-dependent. It can be used for things like index entries or explicit descriptive markup (like program identifiers).

2020-11-04 13:17 UTC, rnestler reviewed
LGTM apart from the minor nitpick about using \`foo\` which has an unclear meaning in restructured text.

2020-11-04 13:18 UTC, rnestler approved these changes

2020-11-04 14:01 UTC, Zifzaf commented on README-ARDUINO.rst
> +Serial Monitor`. If everything worked fine and your Arduino is still connected
Andreas suggested that, I think we both didn't notice that it doesn't render in the rst and were thinking about md.

2020-11-04 14:09 UTC, Zifzaf commented on README-ARDUINO.rst
> +Serial Monitor`. If everything worked fine and your Arduino is still connected
Fixed it.

2020-11-04 15:07 UTC, merged