Implement get serial command
Sensirion/embedded-svm40 pull request #7
Opened 2020-09-02 09:06 UTC by Zifzaf

Check the following:

 - [ ] Breaking changes marked in commit message
 - [ ] Changelog updated
 - [ ] Code style cleaned (ran `make style-fix`)
 - [ ] Tested on actual hardware

2020-09-02 09:49 UTC, rnestler commented
From one of the commit messages:

> - Fix error variable in sample usage to be initialised at the beginning
  of main.

That's not what you did: You changed it to be *declared* at the beginning of main.

2020-09-02 09:53 UTC, abrauchli requested changes

2020-09-02 09:53 UTC, abrauchli commented on svm40/svm40.c
> +    int16_t error;
I'd recommend a blank line between declaration block and implementation - we don't do it universally but I try to do it.

2020-09-02 09:53 UTC, abrauchli commented on svm40/svm40.c
> +    sensirion_sleep_usec(1);
Be prepared to answer the "Where is this documented?" question with timings.. Could we make it a constant?

2020-09-02 09:53 UTC, abrauchli commented on svm40/svm40.c
> +        SVM40_MAX_SERIAL_LEN / SENSIRION_WORD_SIZE);
have a look at the `SENSIRION_NUM_WORDS()` macro

2020-09-02 09:53 UTC, abrauchli commented on svm40/svm40.h
> +/*
use `/**` to initiate a docstr comment - i.e. a comment that could be used for automated processing such as for generated documentation.

2020-09-02 09:53 UTC, abrauchli commented on svm40/svm40.h
> + * 				 (zero terminated). Musit be at least
```suggestion
 * 				 The string is guaranteed to be zero terminated. It must be at least
```

2020-09-02 09:53 UTC, abrauchli commented on svm40/svm40_example_usage.c
> +    char serial_id[SVM40_MAX_SERIAL_LEN];
I'd declare it at top of the function (this was mandatory for C89, which don't have to be compatible with, but I still like it :) )

2020-09-02 09:53 UTC, abrauchli commented on svm40/svm40_example_usage.c
> +    if (error == NO_ERROR) {
There's not output on error. I generally prefer for the error handling case to be first and the no-error flow to be after:
e.g.

```cpp
if (error != NO_ERROR) {
    printf("Error reading SVM40 serial: %i\n", error);
} else {
    // ...
}
```

2020-09-02 09:53 UTC, abrauchli commented on svm40/svm40_example_usage.c
> +        for (uint16_t i = 0; i < SVM40_MAX_SERIAL_LEN - 2; i++) {
I don't know if we standardize this, again coming from C89 style, I prefer the declaration of `i` at the top of the function... @rnestler ?

2020-09-02 11:04 UTC, Zifzaf commented on svm40/svm40.c
> +    int16_t error;
Okay noted :)

2020-09-02 11:21 UTC, Zifzaf commented on svm40/svm40.c
> +    sensirion_sleep_usec(1);
Changed to constant.

2020-09-02 13:58 UTC, rnestler requested changes

2020-09-02 13:58 UTC, rnestler commented on svm40/svm40.c
> +    sensirion_sleep_usec(SVM40_DELAY_GET_SERIAL_NUMBER);
Is this delay really needed?

2020-09-02 13:58 UTC, rnestler commented on svm40/svm40_example_usage.c
> +            printf("%c", serial_id[i]);
Just use `%s` in the format string instead of the for loop and printing each character by its own.

2020-09-02 20:40 UTC, abrauchli commented on svm40/svm40_example_usage.c
> +            printf("%c", serial_id[i]);
`printf("Serial Number: %s", serial_id);` - sorry, I should have seen that, too 🐤

2020-09-03 05:49 UTC, Zifzaf commented on svm40/svm40.c
> +    sensirion_sleep_usec(SVM40_DELAY_GET_SERIAL_NUMBER);
https://rd-hw.gitlab.sensirion.lokal/-/Phoenix/phoenix2-firmware/-/jobs/327019/artifacts/documentation/i2c/SVM40_I2cInterface.html

Yes it's in the specification as read delay of one millisecond!

2020-09-03 11:17 UTC, rnestler commented on svm40/svm40_example_usage.c
> +    uint16_t i;
This seems like an unused variable, no?

2020-09-03 14:26 UTC, Zifzaf commented on svm40/svm40_example_usage.c
> +    uint16_t i;
Yes now it is, will fix it.

2020-09-03 15:49 UTC, rnestler commented on svm40/svm40.c
> +    sensirion_sleep_usec(SVM40_DELAY_GET_SERIAL_NUMBER);
So we should add it to all the commands then.

2020-09-03 15:50 UTC, rnestler commented on svm40/svm40.c
> +    sensirion_sleep_usec(SVM40_DELAY_GET_SERIAL_NUMBER);
Maybe `#define` a single `SVM40_READ_DELAY` instead of having 4 different defines with the same value.

2020-09-03 15:50 UTC, rnestler approved these changes

2020-09-04 07:08 UTC, abrauchli approved these changes

2020-09-04 08:32 UTC, merged