Implement device reset command
Sensirion/embedded-svm40 pull request #8
Opened 2020-09-02 11:00 UTC by Zifzaf

Check the following:

 - [ ] Breaking changes marked in commit message
 - [ ] Changelog updated
 - [ ] Code style cleaned (ran `make style-fix`)
 - [ ] Tested on actual hardware

2020-09-02 14:03 UTC, rnestler commented on svm40/svm40.c
> +    return sensirion_i2c_write_cmd(SVM40_I2C_ADDRESS, SVM40_CMD_DEVICE_RESET);
Should we wait the 100ms after the reset? I'd at least add a `#define` with the 100ms constant to the header file.

2020-09-02 20:36 UTC, abrauchli commented on svm40/svm40.c
> +    return sensirion_i2c_write_cmd(SVM40_I2C_ADDRESS, SVM40_CMD_DEVICE_RESET);
For the SPS30 we don't wait either on reset.. just making the constant public is fine IMO

2020-09-02 20:43 UTC, abrauchli requested changes
..we're getting closer to the perfect commit though 👍

2020-09-03 06:06 UTC, Zifzaf commented on svm40/svm40.c
> +    return sensirion_i2c_write_cmd(SVM40_I2C_ADDRESS, SVM40_CMD_DEVICE_RESET);
Added constant in the header file. Is this okay? Anything else?

2020-09-03 15:53 UTC, rnestler reviewed
Except for the naming it LGTM :rainbow:

2020-09-03 15:53 UTC, rnestler commented on svm40/svm40.c
> +int16_t svm40_reset(void) {
I'd keep the function name as close to the datasheet as possible. So I'd call it `device_reset` instead of just `reset`.

2020-09-04 10:06 UTC, abrauchli approved these changes

2020-09-04 10:06 UTC, abrauchli commented on svm40/svm40.c
> +    return sensirion_i2c_write_cmd(SVM40_I2C_ADDRESS, SVM40_CMD_DEVICE_RESET);
no, this is resolved.

2020-09-04 13:44 UTC, merged