Add read_measured_values_as_integers_with_raw_parameters Function
Sensirion/embedded-svm40 pull request #9
Opened 2020-09-02 14:09 UTC by Zifzaf

- Add and implement function
  read_measured_values_as_integers_with_raw_parameters to svm40.h
  and svm40.c file.
- Update Changelog.

Check the following:

 - [ ] Breaking changes marked in commit message
 - [ ] Changelog updated
 - [ ] Code style cleaned (ran `make style-fix`)
 - [ ] Tested on actual hardware

2020-09-02 20:31 UTC, abrauchli requested changes

2020-09-02 20:31 UTC, abrauchli commented on svm40/svm40.c
> +    error = sensirion_i2c_read_words(SVM40_I2C_ADDRESS, (uint16_t*)buffer,
instead of casting a pointer, I think it's better to declare the buffer as uint16_t[], since that's how it's actually used, and then cast the individual values below. That avoids casting a pointer.

2020-09-02 20:31 UTC, abrauchli commented on svm40/svm40.h
> + * @param   voc_index           VOC algorithm output with a scaling value of 10.
This might be misleading since the param name `voc_index` doesn't imply that the value is scaled. Would be good to indicate in what range the value is (is the index in the range 0..500, so the scaled values are 0..5000?)

I'm not a fan of those scaled values with somewhat arbitrary scaling factors... I understand fixed point scaling (10, 100, ...) but 200 for temperature goes against the temperature channels we output from other drivers - I'd try to stay consistent here, no matter what the sensor spews out even if that means that we have to use a larger data type. In any case, @rnestler has the final say..

2020-09-02 20:31 UTC, abrauchli commented on svm40/svm40.h
> + * Returns the new measurement results as integers with raw values added.
```suggestion
 * Returns the new measurement results as integers along with the raw gas signal and uncompensated RH/T values.
```
would you mind double checking if the datasheet calls it gas signal or voc ticks?

2020-09-02 20:31 UTC, abrauchli commented on svm40/svm40.h
> + * @param   relative_humidity   Uncompensated raw humidity in % RH as read from
```suggestion
 * @param   uncompensated_relative_humidity   Uncompensated raw humidity in %RH as read from
```

2020-09-02 20:31 UTC, abrauchli commented on svm40/svm40.h
> + * @param   temperature_raw     Uncompensated raw temperature in degrees celsius
```suggestion
 * @param   uncompensated_temperature     Uncompensated raw temperature in degrees celsius
```

2020-09-02 20:31 UTC, abrauchli commented on svm40/svm40.h
> + * @param   relative_humidity   Uncompensated raw humidity in % RH as read from
..also change below and in source

2020-09-02 20:31 UTC, abrauchli commented on svm40/svm40.h
> +int16_t svm40_read_measured_values_as_integers_with_raw_parameters(
```suggestion
int16_t svm40_read_measured_values_as_integers_with_raw_params(
```
slightly shorter.. I still think it's too long and I'm not too happy with the "raw params" part, but can't see anything better either :/

2020-09-03 06:11 UTC, Zifzaf commented on svm40/svm40.c
> +    error = sensirion_i2c_read_words(SVM40_I2C_ADDRESS, (uint16_t*)buffer,
Okay are you sure? It's done the same way in the read_measured_values_as_integers function and we would replace one pointer cast and one type cast with 5 typecasts. Just checking ;)

2020-09-03 06:14 UTC, Zifzaf commented on svm40/svm40.h
> + * @param   voc_index           VOC algorithm output with a scaling value of 10.
That's actually a copy from the method read_measured_values_as_integers so if we change it we should change it in both places.

2020-09-03 06:18 UTC, Zifzaf commented on svm40/svm40.h
> + * Returns the new measurement results as integers with raw values added.
It's voc_ticks so I changed it to " ... as integers along with the raw voc ticks and uncompensated RH/T values."

2020-09-03 11:45 UTC, abrauchli commented on svm40/svm40.c
> +    error = sensirion_i2c_read_words(SVM40_I2C_ADDRESS, (uint16_t*)buffer,
Fair point, but yes, a lot more things can go wrong when casting pointers.. I'd also change it above (separate commit, but can be in this MR)
@rnestler do you have an opinion?

2020-09-03 15:55 UTC, rnestler commented on svm40/svm40.c
> +    error = sensirion_i2c_read_words(SVM40_I2C_ADDRESS, (uint16_t*)buffer,
I was actually thorn between the two solutions as well: Casting the pointer or casting the values. Generally I agree with @abrauchli that pointer casts are more dangerous, so we should probably change it in `read_measured_values_as_integers` as well for consistency.

2020-09-03 15:58 UTC, rnestler commented on svm40/svm40.h
> + * @param   voc_index           VOC algorithm output with a scaling value of 10.
I'd like to stay as close to the data sheet as possible for the low level command implementations (With the prospect of one day generating these functions from the interface description). I'd rather provide a casting function which converts to float with the correct scaling factor.

2020-09-04 07:05 UTC, abrauchli approved these changes

2020-09-04 08:36 UTC, merged